import jsPDF from "jspdf";
import { ImplementationPlan } from "@/types/implementation";
import { generateLovableRebuildPrompt } from "./generateLovablePrompt";
import { isValidAnalysisSourceUrl, sanitizeAnalysisUrl } from "./urlValidation";
import { CREDIBILITY_STANDARD } from "@/components/scoring/ScoreCredibilityStatement";

// Branding options for white-label PDFs
export interface PdfBranding {
  logoUrl?: string | null;
  footerText?: string | null;
  primaryColor?: string | null;
  accentColor?: string | null;
}

// Color palette (RGB values) - matches Analysis PDF
const colors = {
  primary: [59, 130, 246], // Blue
  primaryLight: [239, 246, 255], // Light blue background
  primaryDark: [37, 99, 235], // Darker blue
  success: [34, 197, 94], // Green
  successLight: [240, 253, 244],
  warning: [251, 191, 36], // Amber/Yellow
  warningLight: [254, 252, 232],
  accent: [139, 92, 246], // Purple
  accentLight: [245, 243, 255],
  textPrimary: [30, 41, 59], // Slate 800
  textSecondary: [71, 85, 105], // Slate 600
  textMuted: [148, 163, 184], // Slate 400
  cardBg: [248, 250, 252], // Slate 50
  border: [226, 232, 240], // Slate 200
  white: [255, 255, 255],
};

// Icon labels for different sections (simple letters that work with standard fonts)
const sectionIcons: Record<string, string> = {
  hero: "H",
  pages: "P",
  forms: "F",
  seo: "S",
  design: "D",
  technical: "T",
  checklist: "C",
};

export function generateImplementationPdf(plan: ImplementationPlan, url: string, branding?: PdfBranding) {
  // GUARDRAIL: Validate that URL is not a Lovable/deployment URL
  const validatedUrl = isValidAnalysisSourceUrl(url) ? url : sanitizeAnalysisUrl(url, "Original website URL unavailable");
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;
  let currentPage = 1;

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > 270) {
      addFooter();
      doc.addPage();
      currentPage++;
      y = 20;
    }
  };

  // Add footer to each page
  const addFooter = () => {
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    doc.setFontSize(8);
    doc.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
    const footerText = branding?.footerText || "Generated by OptimizeMySuite";
    doc.text(footerText, margin, pageHeight - 10);
    doc.text(`Page ${currentPage}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };

  // Section header with icon and background
  const addSectionHeader = (title: string, iconKey: string) => {
    addPageIfNeeded(30);
    
    // Section card background
    doc.setFillColor(colors.cardBg[0], colors.cardBg[1], colors.cardBg[2]);
    doc.roundedRect(margin, y - 5, contentWidth, 22, 4, 4, "F");
    
    // Icon circle
    doc.setFillColor(colors.primaryLight[0], colors.primaryLight[1], colors.primaryLight[2]);
    doc.circle(margin + 12, y + 6, 8, "F");
    doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.circle(margin + 12, y + 6, 5, "F");
    
    // Icon letter (centered in circle)
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    const icon = sectionIcons[iconKey] || "X";
    doc.text(icon, margin + 12, y + 7.5, { align: "center" });
    
    // Title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
    doc.text(title, margin + 26, y + 9);
    
    y += 28;
  };

  // Subsection header
  const addSubsectionHeader = (title: string) => {
    addPageIfNeeded(15);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text(title, margin + 5, y);
    y += 7;
  };

  // Text block in a card
  const addTextCard = (text: string, bgColor: number[] = colors.primaryLight) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, contentWidth - 24);
    const blockHeight = lines.length * 5 + 12;
    addPageIfNeeded(blockHeight);
    
    // Card background
    doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
    doc.roundedRect(margin, y - 3, contentWidth, blockHeight, 3, 3, "F");
    
    // Text
    doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
    lines.forEach((line: string, index: number) => {
      doc.text(line, margin + 12, y + 6 + index * 5);
    });
    y += blockHeight + 4;
  };

  // CTA or highlight card with accent color
  const addHighlightCard = (label: string, text: string) => {
    addPageIfNeeded(25);
    
    // Card background with accent
    doc.setFillColor(colors.accentLight[0], colors.accentLight[1], colors.accentLight[2]);
    doc.roundedRect(margin, y - 3, contentWidth, 22, 3, 3, "F");
    
    // Accent stripe
    doc.setFillColor(colors.accent[0], colors.accent[1], colors.accent[2]);
    doc.roundedRect(margin, y - 3, 4, 22, 2, 2, "F");
    
    // Label
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.accent[0], colors.accent[1], colors.accent[2]);
    doc.text(label.toUpperCase(), margin + 12, y + 4);
    
    // Text
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
    const lines = doc.splitTextToSize(text, contentWidth - 20);
    doc.text(lines[0], margin + 12, y + 12);
    
    y += 26;
  };

  // Bullet item with icon
  const addBulletItem = (text: string, bulletColor: number[] = colors.primary) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, contentWidth - 18);
    const blockHeight = lines.length * 5 + 4;
    addPageIfNeeded(blockHeight);
    
    // Bullet circle
    doc.setFillColor(bulletColor[0], bulletColor[1], bulletColor[2]);
    doc.circle(margin + 6, y + 1, 2, "F");
    
    // Text
    doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
    lines.forEach((line: string, index: number) => {
      doc.text(line, margin + 14, y + 3 + index * 5);
    });
    y += blockHeight;
  };

  // Numbered item with badge
  const addNumberedItem = (num: number, text: string, priority: boolean = false) => {
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(text, contentWidth - 22);
    const blockHeight = lines.length * 5 + 8;
    addPageIfNeeded(blockHeight);
    
    // Number badge
    const badgeColor = priority ? colors.warning : colors.primary;
    doc.setFillColor(badgeColor[0], badgeColor[1], badgeColor[2]);
    doc.circle(margin + 8, y + 4, 6, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(num.toString(), margin + 8, y + 6, { align: "center" });
    
    // Text
    doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    lines.forEach((line: string, index: number) => {
      doc.text(line, margin + 20, y + 5 + index * 5);
    });
    y += blockHeight;
  };

  // Key-value pair (label + value)
  const addKeyValue = (label: string, value: string) => {
    addPageIfNeeded(18);
    
    // Light background
    doc.setFillColor(colors.cardBg[0], colors.cardBg[1], colors.cardBg[2]);
    const lines = doc.splitTextToSize(value, contentWidth - 15);
    const blockHeight = lines.length * 5 + 12;
    doc.roundedRect(margin, y - 2, contentWidth, blockHeight, 2, 2, "F");
    
    // Label
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
    doc.text(label.toUpperCase(), margin + 8, y + 4);
    
    // Value
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
    lines.forEach((line: string, index: number) => {
      doc.text(line, margin + 8, y + 10 + index * 5);
    });
    y += blockHeight + 3;
  };

  // Service card
  const addServiceCard = (serviceName: string, description: string, cta: string) => {
    addPageIfNeeded(35);
    
    // Card background
    doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    doc.roundedRect(margin, y - 2, contentWidth, 32, 3, 3, "FD");
    
    // Service name
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
    doc.text(serviceName, margin + 8, y + 6);
    
    // Description
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
    const descLines = doc.splitTextToSize(description, contentWidth - 20);
    doc.text(descLines[0], margin + 8, y + 14);
    
    // CTA badge
    doc.setFillColor(colors.successLight[0], colors.successLight[1], colors.successLight[2]);
    doc.roundedRect(margin + 8, y + 20, 60, 8, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.success[0], colors.success[1], colors.success[2]);
    doc.text(`CTA: ${cta}`, margin + 12, y + 25);
    
    y += 38;
  };

  // Color swatch
  const addColorSwatch = (label: string, color: string, x: number, swatchY: number) => {
    doc.setFillColor(colors.cardBg[0], colors.cardBg[1], colors.cardBg[2]);
    doc.roundedRect(x, swatchY, 50, 28, 3, 3, "F");
    
    // Color circle
    doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.circle(x + 15, swatchY + 10, 6, "F");
    
    // Label
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
    doc.text(label.toUpperCase(), x + 5, swatchY + 22);
    
    // Color value
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
    const shortColor = color.length > 12 ? color.substring(0, 12) + "..." : color;
    doc.text(shortColor, x + 25, swatchY + 10);
  };

  // ============ HEADER ============
  // Blue header bar
  doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  // Gradient effect
  doc.setFillColor(colors.primaryDark[0], colors.primaryDark[1], colors.primaryDark[2]);
  doc.rect(0, 0, pageWidth, 5, "F");
  
  // Header logo or icon
  let titleStartX = margin + 24;
  if (branding?.logoUrl) {
    try {
      // Add logo image (base64 or URL)
      doc.addImage(branding.logoUrl, "PNG", margin + 5, 8, 24, 24);
      titleStartX = margin + 35;
    } catch (e) {
      // Fallback to icon if logo fails
      doc.setFillColor(255, 255, 255);
      doc.circle(margin + 17, 20, 10, "F");
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
      doc.text("O", margin + 17, 23, { align: "center" });
    }
  } else {
    // Default icon - letter "O" for OptimizeMySuite
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 17, 20, 10, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text("O", margin + 17, 23, { align: "center" });
  }
  
  // Header title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("Implementation Pack", titleStartX, 22);
  
  // URL and date (subheader) - uses validated URL
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const displayUrl = validatedUrl.length > 50 ? validatedUrl.substring(0, 50) + "..." : validatedUrl;
  doc.text(`${displayUrl}  •  ${new Date().toLocaleDateString()}`, margin + 24, y + 35);
  
  y = 58;

  // ============ INTRO CARD ============
  doc.setFillColor(colors.successLight[0], colors.successLight[1], colors.successLight[2]);
  doc.roundedRect(margin, y - 5, contentWidth, 22, 4, 4, "F");
  
  // Check icon - draw a checkmark shape
  doc.setFillColor(colors.success[0], colors.success[1], colors.success[2]);
  doc.circle(margin + 12, y + 6, 6, "F");
  // Draw checkmark using lines
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(1.2);
  doc.line(margin + 9, y + 6, margin + 11.5, y + 8.5);
  doc.line(margin + 11.5, y + 8.5, margin + 15, y + 3.5);
  
  // Intro text
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.success[0], colors.success[1], colors.success[2]);
  doc.text("Ready-to-implement recommendations for your website", margin + 24, y + 9);
  
  y += 32;

  // ============ HERO SECTION ============
  addSectionHeader("Hero Section", "hero");
  
  addKeyValue("Headline", plan.heroSection.headline);
  addKeyValue("Subheadline", plan.heroSection.subheadline);
  
  addSubsectionHeader("Supporting Bullets");
  plan.heroSection.supportingBullets.forEach((bullet) => {
    addBulletItem(bullet, colors.success);
  });
  y += 5;
  
  addHighlightCard("Primary CTA", plan.heroSection.primaryCTA);
  addHighlightCard("Secondary CTA", plan.heroSection.secondaryCTA);
  y += 5;

  // ============ KEY PAGES ============
  addSectionHeader("Key Pages Copy", "pages");
  
  // Homepage
  addSubsectionHeader("Homepage");
  addKeyValue("Intro Copy", plan.keyPages.home.intro);
  addKeyValue("Services Overview", plan.keyPages.home.servicesOverview);
  
  addSubsectionHeader("Why Choose Us");
  plan.keyPages.home.whyChooseUs.forEach((item) => {
    addBulletItem(item, colors.success);
  });
  
  addSubsectionHeader("Trust Elements");
  plan.keyPages.home.trustElements.forEach((item) => {
    addBulletItem(item, colors.warning);
  });
  y += 5;

  // Services Page
  if (plan.keyPages.servicesPage.sections.length > 0) {
    addSubsectionHeader("Services Page");
    plan.keyPages.servicesPage.sections.forEach((service) => {
      addServiceCard(service.serviceName, service.shortDescription, service.idealCTA);
    });
    y += 3;
  }

  // About Page
  addSubsectionHeader("About Page");
  addKeyValue("Headline", plan.keyPages.aboutPage.headline);
  addKeyValue("Body Copy", plan.keyPages.aboutPage.body);
  y += 3;

  // Contact Page
  addSubsectionHeader("Contact Page");
  addKeyValue("Headline", plan.keyPages.contactPage.headline);
  addKeyValue("Body Copy", plan.keyPages.contactPage.body);
  y += 5;

  // ============ FORMS & CTAS ============
  addSectionHeader("Forms & CTAs", "forms");
  
  // Primary Phone highlight
  addPageIfNeeded(28);
  doc.setFillColor(colors.warningLight[0], colors.warningLight[1], colors.warningLight[2]);
  doc.roundedRect(margin, y - 3, contentWidth, 24, 4, 4, "F");
  doc.setFillColor(colors.warning[0], colors.warning[1], colors.warning[2]);
  doc.circle(margin + 12, y + 8, 6, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("P", margin + 12, y + 10, { align: "center" }); // P for Phone
  doc.setFontSize(9);
  doc.setTextColor(colors.warning[0], colors.warning[1], colors.warning[2]);
  doc.text("PRIMARY PHONE", margin + 24, y + 5);
  doc.setFontSize(14);
  doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
  doc.text(plan.formsAndCTAs.primaryPhoneNumber, margin + 24, y + 16);
  y += 32;
  
  addSubsectionHeader("Contact Form Fields");
  addTextCard(plan.formsAndCTAs.contactFormSpec.fields.join("  •  "));
  addTextCard(`Note: ${plan.formsAndCTAs.contactFormSpec.notes}`, colors.warningLight);
  
  addSubsectionHeader("CTA Buttons");
  plan.formsAndCTAs.ctaButtons.forEach((cta) => {
    addBulletItem(cta, colors.accent);
  });
  
  addSubsectionHeader("Placement Guidelines");
  plan.formsAndCTAs.placementGuidelines.forEach((guide) => {
    addBulletItem(guide);
  });
  y += 5;

  // ============ SEO SETUP ============
  addSectionHeader("SEO Setup", "seo");
  
  addKeyValue("Homepage Title Tag", plan.seoSetup.home.title);
  addKeyValue("Homepage Meta Description", plan.seoSetup.home.metaDescription);
  addKeyValue("Homepage H1", plan.seoSetup.home.h1);
  
  addSubsectionHeader("Other SEO Suggestions");
  plan.seoSetup.otherSuggestions.forEach((sug) => {
    addBulletItem(sug, colors.success);
  });
  
  addSubsectionHeader("Image Alt Text Examples");
  plan.seoSetup.imageAltTextExamples.forEach((ex) => {
    addTextCard(`${ex.forImageType}: alt="${ex.altText}"`, colors.cardBg);
  });
  y += 5;

  // ============ DESIGN & LAYOUT ============
  addSectionHeader("Design & Layout Tweaks", "design");
  
  addSubsectionHeader("Suggested Color Palette");
  addPageIfNeeded(40);
  
  // Color swatches in a row
  addColorSwatch("Primary", plan.designAndLayout.colorPaletteSuggestion.primary, margin, y);
  addColorSwatch("Secondary", plan.designAndLayout.colorPaletteSuggestion.secondary, margin + 55, y);
  addColorSwatch("Accent", plan.designAndLayout.colorPaletteSuggestion.accent, margin + 110, y);
  y += 35;
  
  addSubsectionHeader("Layout Changes");
  plan.designAndLayout.layoutChanges.forEach((change) => {
    addBulletItem(change);
  });
  y += 5;

  // ============ TECHNICAL FIXES ============
  addSectionHeader("Technical Fixes", "technical");
  
  addSubsectionHeader("Tasks");
  plan.technicalFixes.tasks.forEach((task) => {
    addBulletItem(task, colors.warning);
  });
  
  addSubsectionHeader("Priority Order");
  plan.technicalFixes.priorityOrder.forEach((priority, i) => {
    addNumberedItem(i + 1, priority, true);
  });
  y += 5;

  // ============ EXECUTION CHECKLIST ============
  addSectionHeader("Execution Checklist", "checklist");
  
  // Checklist intro card
  addPageIfNeeded(20);
  doc.setFillColor(colors.successLight[0], colors.successLight[1], colors.successLight[2]);
  doc.roundedRect(margin, y - 3, contentWidth, 16, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.success[0], colors.success[1], colors.success[2]);
  doc.text(`${plan.executionChecklist.length} action items to implement`, margin + 10, y + 6);
  y += 22;
  
  plan.executionChecklist.forEach((item, i) => {
    addNumberedItem(i + 1, item);
  });

  // ============ SCORE CREDIBILITY STATEMENT ============
  y += 8;
  addPageIfNeeded(80);
  
  // Section header
  doc.setFillColor(colors.primaryLight[0], colors.primaryLight[1], colors.primaryLight[2]);
  doc.roundedRect(margin, y - 5, contentWidth, 22, 4, 4, "F");
  
  // Shield icon
  doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.circle(margin + 12, y + 6, 6, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("✓", margin + 12, y + 8, { align: "center" });
  
  // Title
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
  doc.text(CREDIBILITY_STANDARD.intro, margin + 24, y + 9);
  y += 28;
  
  // Description
  addPageIfNeeded(25);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
  const descLines = doc.splitTextToSize(CREDIBILITY_STANDARD.description, contentWidth - 10);
  descLines.forEach((line: string, index: number) => {
    doc.text(line, margin + 5, y + index * 5);
  });
  y += descLines.length * 5 + 8;
  
  // Bullets
  CREDIBILITY_STANDARD.bullets.forEach((bullet) => {
    addBulletItem(bullet, colors.primary);
  });
  
  // Footer text
  y += 5;
  addPageIfNeeded(20);
  doc.setFillColor(colors.cardBg[0], colors.cardBg[1], colors.cardBg[2]);
  const credFooterLines = doc.splitTextToSize(CREDIBILITY_STANDARD.footer, contentWidth - 16);
  const credFooterHeight = credFooterLines.length * 5 + 10;
  doc.roundedRect(margin, y - 3, contentWidth, credFooterHeight, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
  credFooterLines.forEach((line: string, index: number) => {
    doc.text(line, margin + 8, y + 5 + index * 5);
  });
  y += credFooterHeight + 8;

  // ============ LOVABLE REBUILD PROMPTS (OPTIONAL) ============
  y += 10;
  addPageIfNeeded(60);
  
  // Section header with dashed border style
  doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
  doc.setLineDashPattern([3, 2], 0);
  doc.roundedRect(margin, y - 5, contentWidth, 22, 4, 4, "S");
  doc.setLineDashPattern([], 0);
  
  // Icon
  doc.setFillColor(colors.accentLight[0], colors.accentLight[1], colors.accentLight[2]);
  doc.circle(margin + 12, y + 6, 8, "F");
  doc.setFillColor(colors.accent[0], colors.accent[1], colors.accent[2]);
  doc.circle(margin + 12, y + 6, 5, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("◈", margin + 12, y + 8, { align: "center" });
  
  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
  doc.text("Lovable Website Rebuild Prompts (Optional)", margin + 26, y + 9);
  y += 28;
  
  // Disclaimer box
  addPageIfNeeded(25);
  doc.setFillColor(colors.accentLight[0], colors.accentLight[1], colors.accentLight[2]);
  doc.roundedRect(margin, y - 3, contentWidth, 18, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
  const disclaimerText = "This rebuild prompt is optional and intended for internal use when recreating a website in Lovable. It does not modify the existing Implementation Plan.";
  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 10);
  doc.text(disclaimerLines, margin + 5, y + 5);
  y += 25;
  
  // Prompt label
  addPageIfNeeded(15);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.textSecondary[0], colors.textSecondary[1], colors.textSecondary[2]);
  doc.text("Copy & Paste into Lovable:", margin, y);
  y += 8;
  
  // Generate the Lovable prompt - uses validated URL
  const lovablePrompt = generateLovableRebuildPrompt(plan, validatedUrl);
  
  // Split prompt into lines for PDF rendering - FULL PROMPT, NO TRUNCATION
  const promptLines = doc.splitTextToSize(lovablePrompt, contentWidth - 10);
  
  // Calculate required height for full prompt (no truncation)
  const lineHeight = 4;
  const paddingTop = 6;
  const paddingBottom = 6;
  const promptHeight = (promptLines.length * lineHeight) + paddingTop + paddingBottom;
  
  // Add pages as needed to fit the entire prompt
  let linesRemaining = promptLines.length;
  let lineIndex = 0;
  
  while (linesRemaining > 0) {
    // Calculate how many lines fit on current page
    const availableHeight = 270 - y;
    const linesPerPage = Math.floor((availableHeight - paddingTop - paddingBottom) / lineHeight);
    const linesToRender = Math.min(linesRemaining, linesPerPage);
    
    if (linesToRender <= 0) {
      // Not enough space, add new page
      addFooter();
      doc.addPage();
      currentPage++;
      y = 20;
      continue;
    }
    
    // Draw container for this page's portion
    const containerHeight = (linesToRender * lineHeight) + paddingTop + paddingBottom;
    doc.setFillColor(colors.cardBg[0], colors.cardBg[1], colors.cardBg[2]);
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    doc.roundedRect(margin, y - 3, contentWidth, containerHeight, 3, 3, "FD");
    
    // Render lines
    doc.setFontSize(7);
    doc.setFont("courier", "normal");
    doc.setTextColor(colors.textPrimary[0], colors.textPrimary[1], colors.textPrimary[2]);
    
    let lineY = y + paddingTop - 1;
    for (let i = 0; i < linesToRender; i++) {
      doc.text(promptLines[lineIndex + i], margin + 5, lineY);
      lineY += lineHeight;
    }
    
    y += containerHeight + 3;
    lineIndex += linesToRender;
    linesRemaining -= linesToRender;
    
    // If more lines remain, add a new page
    if (linesRemaining > 0) {
      addFooter();
      doc.addPage();
      currentPage++;
      y = 20;
      
      // Add continuation label
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
      doc.text("Lovable Rebuild Prompt (continued):", margin, y);
      y += 10;
    }
  }
  
  y += 5;

  // ============ FINAL FOOTER ============
  addFooter();

  // Save
  const filename = `implementation-pack-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
